//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAC2021SQL.GroupWSProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSGroupResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSGroupResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2021SQL.GroupWSProxy.GroupDetail ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IAC2021SQL.GroupWSProxy.GroupDetail Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupDetail", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class GroupDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2021SQL.GroupWSProxy.Keyword[] KeywordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int IsPublic {
            get {
                return this.IsPublicField;
            }
            set {
                if ((this.IsPublicField.Equals(value) != true)) {
                    this.IsPublicField = value;
                    this.RaisePropertyChanged("IsPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DefaultCode {
            get {
                return this.DefaultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultCodeField, value) != true)) {
                    this.DefaultCodeField = value;
                    this.RaisePropertyChanged("DefaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public IAC2021SQL.GroupWSProxy.Keyword[] Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Keyword", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class Keyword : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string app_identifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int auto_subscribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callback_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2021SQL.GroupWSProxy.CustomField[] fieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int keyword_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subscribed_responseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string keywordcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char isnotifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int communicationcodeidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notifylistemailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int keywordidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char iscallbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int groupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notifylistphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isautosubscribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDripKeywordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnrollmentRestrictedResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HistoryUserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public char active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string app_identifier {
            get {
                return this.app_identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.app_identifierField, value) != true)) {
                    this.app_identifierField = value;
                    this.RaisePropertyChanged("app_identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int auto_subscribe {
            get {
                return this.auto_subscribeField;
            }
            set {
                if ((this.auto_subscribeField.Equals(value) != true)) {
                    this.auto_subscribeField = value;
                    this.RaisePropertyChanged("auto_subscribe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string callback_url {
            get {
                return this.callback_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.callback_urlField, value) != true)) {
                    this.callback_urlField = value;
                    this.RaisePropertyChanged("callback_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IAC2021SQL.GroupWSProxy.CustomField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.fieldsField, value) != true)) {
                    this.fieldsField = value;
                    this.RaisePropertyChanged("fields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int keyword_type {
            get {
                return this.keyword_typeField;
            }
            set {
                if ((this.keyword_typeField.Equals(value) != true)) {
                    this.keyword_typeField = value;
                    this.RaisePropertyChanged("keyword_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                if ((object.ReferenceEquals(this.noteField, value) != true)) {
                    this.noteField = value;
                    this.RaisePropertyChanged("note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string subscribed_response {
            get {
                return this.subscribed_responseField;
            }
            set {
                if ((object.ReferenceEquals(this.subscribed_responseField, value) != true)) {
                    this.subscribed_responseField = value;
                    this.RaisePropertyChanged("subscribed_response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                if ((object.ReferenceEquals(this.wordField, value) != true)) {
                    this.wordField = value;
                    this.RaisePropertyChanged("word");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string keywordcode {
            get {
                return this.keywordcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordcodeField, value) != true)) {
                    this.keywordcodeField = value;
                    this.RaisePropertyChanged("keywordcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public char isnotify {
            get {
                return this.isnotifyField;
            }
            set {
                if ((this.isnotifyField.Equals(value) != true)) {
                    this.isnotifyField = value;
                    this.RaisePropertyChanged("isnotify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string companycode {
            get {
                return this.companycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.companycodeField, value) != true)) {
                    this.companycodeField = value;
                    this.RaisePropertyChanged("companycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string groupcode {
            get {
                return this.groupcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.groupcodeField, value) != true)) {
                    this.groupcodeField = value;
                    this.RaisePropertyChanged("groupcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public int communicationcodeid {
            get {
                return this.communicationcodeidField;
            }
            set {
                if ((this.communicationcodeidField.Equals(value) != true)) {
                    this.communicationcodeidField = value;
                    this.RaisePropertyChanged("communicationcodeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string notifylistemail {
            get {
                return this.notifylistemailField;
            }
            set {
                if ((object.ReferenceEquals(this.notifylistemailField, value) != true)) {
                    this.notifylistemailField = value;
                    this.RaisePropertyChanged("notifylistemail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public int keywordid {
            get {
                return this.keywordidField;
            }
            set {
                if ((this.keywordidField.Equals(value) != true)) {
                    this.keywordidField = value;
                    this.RaisePropertyChanged("keywordid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public char iscallback {
            get {
                return this.iscallbackField;
            }
            set {
                if ((this.iscallbackField.Equals(value) != true)) {
                    this.iscallbackField = value;
                    this.RaisePropertyChanged("iscallback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public int groupid {
            get {
                return this.groupidField;
            }
            set {
                if ((this.groupidField.Equals(value) != true)) {
                    this.groupidField = value;
                    this.RaisePropertyChanged("groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string notifylistphone {
            get {
                return this.notifylistphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.notifylistphoneField, value) != true)) {
                    this.notifylistphoneField = value;
                    this.RaisePropertyChanged("notifylistphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public int isautosubscribe {
            get {
                return this.isautosubscribeField;
            }
            set {
                if ((this.isautosubscribeField.Equals(value) != true)) {
                    this.isautosubscribeField = value;
                    this.RaisePropertyChanged("isautosubscribe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string KeywordTypeName {
            get {
                return this.KeywordTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordTypeNameField, value) != true)) {
                    this.KeywordTypeNameField = value;
                    this.RaisePropertyChanged("KeywordTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public int IsDripKeyword {
            get {
                return this.IsDripKeywordField;
            }
            set {
                if ((this.IsDripKeywordField.Equals(value) != true)) {
                    this.IsDripKeywordField = value;
                    this.RaisePropertyChanged("IsDripKeyword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string EnrollmentRestrictedResponse {
            get {
                return this.EnrollmentRestrictedResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.EnrollmentRestrictedResponseField, value) != true)) {
                    this.EnrollmentRestrictedResponseField = value;
                    this.RaisePropertyChanged("EnrollmentRestrictedResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public int HistoryUserID {
            get {
                return this.HistoryUserIDField;
            }
            set {
                if ((this.HistoryUserIDField.Equals(value) != true)) {
                    this.HistoryUserIDField = value;
                    this.RaisePropertyChanged("HistoryUserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomField", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class CustomField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SBTService/ServiceContracts/", ConfigurationName="GroupWSProxy.IGroup")]
    public interface IGroup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReadGroup", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReadGroupResponse")]
        IAC2021SQL.GroupWSProxy.WSGroupResponse ReadGroup(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReadGroup", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReadGroupResponse")]
        System.Threading.Tasks.Task<IAC2021SQL.GroupWSProxy.WSGroupResponse> ReadGroupAsync(string securityToken, string orgCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupChannel : IAC2021SQL.GroupWSProxy.IGroup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupClient : System.ServiceModel.ClientBase<IAC2021SQL.GroupWSProxy.IGroup>, IAC2021SQL.GroupWSProxy.IGroup {
        
        public GroupClient() {
        }
        
        public GroupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IAC2021SQL.GroupWSProxy.WSGroupResponse ReadGroup(string securityToken, string orgCode) {
            return base.Channel.ReadGroup(securityToken, orgCode);
        }
        
        public System.Threading.Tasks.Task<IAC2021SQL.GroupWSProxy.WSGroupResponse> ReadGroupAsync(string securityToken, string orgCode) {
            return base.Channel.ReadGroupAsync(securityToken, orgCode);
        }
    }
}
