//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAC2018SQL.GeneralWSProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReportInboundMessagesResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSReportInboundMessagesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSCarrierPhoneRow[] ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IAC2018SQL.GeneralWSProxy.WSCarrierPhoneRow[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSCarrierPhoneRow", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSCarrierPhoneRow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InternationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LandlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarrierCode {
            get {
                return this.CarrierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierCodeField, value) != true)) {
                    this.CarrierCodeField = value;
                    this.RaisePropertyChanged("CarrierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Carrier {
            get {
                return this.CarrierField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierField, value) != true)) {
                    this.CarrierField = value;
                    this.RaisePropertyChanged("Carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool International {
            get {
                return this.InternationalField;
            }
            set {
                if ((this.InternationalField.Equals(value) != true)) {
                    this.InternationalField = value;
                    this.RaisePropertyChanged("International");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Invalid {
            get {
                return this.InvalidField;
            }
            set {
                if ((this.InvalidField.Equals(value) != true)) {
                    this.InvalidField = value;
                    this.RaisePropertyChanged("Invalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool Landline {
            get {
                return this.LandlineField;
            }
            set {
                if ((this.LandlineField.Equals(value) != true)) {
                    this.LandlineField = value;
                    this.RaisePropertyChanged("Landline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSCarrierLookupResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSCarrierLookupResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSCarrierPhoneRow[] ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IAC2018SQL.GeneralWSProxy.WSCarrierPhoneRow[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSOrganizationTreeResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSOrganizationTreeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSOrganization ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IAC2018SQL.GeneralWSProxy.WSOrganization Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSOrganization", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSOrganization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgStructureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateAbbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactMobilePhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSOrganization[] organizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.GroupWS[] GroupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgStructureName {
            get {
                return this.OrgStructureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgStructureNameField, value) != true)) {
                    this.OrgStructureNameField = value;
                    this.RaisePropertyChanged("OrgStructureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string CommunicationCode {
            get {
                return this.CommunicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationCodeField, value) != true)) {
                    this.CommunicationCodeField = value;
                    this.RaisePropertyChanged("CommunicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIDField, value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string StateAbbr {
            get {
                return this.StateAbbrField;
            }
            set {
                if ((object.ReferenceEquals(this.StateAbbrField, value) != true)) {
                    this.StateAbbrField = value;
                    this.RaisePropertyChanged("StateAbbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string ContactFName {
            get {
                return this.ContactFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactFNameField, value) != true)) {
                    this.ContactFNameField = value;
                    this.RaisePropertyChanged("ContactFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string ContactLName {
            get {
                return this.ContactLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactLNameField, value) != true)) {
                    this.ContactLNameField = value;
                    this.RaisePropertyChanged("ContactLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string ContactPhoneNo {
            get {
                return this.ContactPhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneNoField, value) != true)) {
                    this.ContactPhoneNoField = value;
                    this.RaisePropertyChanged("ContactPhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string ContactMobilePhoneNo {
            get {
                return this.ContactMobilePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactMobilePhoneNoField, value) != true)) {
                    this.ContactMobilePhoneNoField = value;
                    this.RaisePropertyChanged("ContactMobilePhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string ContactEmailID {
            get {
                return this.ContactEmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailIDField, value) != true)) {
                    this.ContactEmailIDField = value;
                    this.RaisePropertyChanged("ContactEmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public IAC2018SQL.GeneralWSProxy.WSOrganization[] organization {
            get {
                return this.organizationField;
            }
            set {
                if ((object.ReferenceEquals(this.organizationField, value) != true)) {
                    this.organizationField = value;
                    this.RaisePropertyChanged("organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public IAC2018SQL.GeneralWSProxy.GroupWS[] Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupWS", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class GroupWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSubscriptionPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StackOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.KeywordWS[] KeywordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupCode {
            get {
                return this.GroupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupCodeField, value) != true)) {
                    this.GroupCodeField = value;
                    this.RaisePropertyChanged("GroupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSubscriptionPublic {
            get {
                return this.IsSubscriptionPublicField;
            }
            set {
                if ((this.IsSubscriptionPublicField.Equals(value) != true)) {
                    this.IsSubscriptionPublicField = value;
                    this.RaisePropertyChanged("IsSubscriptionPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StackOrder {
            get {
                return this.StackOrderField;
            }
            set {
                if ((this.StackOrderField.Equals(value) != true)) {
                    this.StackOrderField = value;
                    this.RaisePropertyChanged("StackOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CommunicationCode {
            get {
                return this.CommunicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationCodeField, value) != true)) {
                    this.CommunicationCodeField = value;
                    this.RaisePropertyChanged("CommunicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public IAC2018SQL.GeneralWSProxy.KeywordWS[] Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordWS", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class KeywordWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyWordNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallbackURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int App_IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscribedResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeywordTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsAutoSubscribeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeywordCode {
            get {
                return this.KeywordCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordCodeField, value) != true)) {
                    this.KeywordCodeField = value;
                    this.RaisePropertyChanged("KeywordCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string KeyWordName {
            get {
                return this.KeyWordNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyWordNameField, value) != true)) {
                    this.KeyWordNameField = value;
                    this.RaisePropertyChanged("KeyWordName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string KeywordNote {
            get {
                return this.KeywordNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordNoteField, value) != true)) {
                    this.KeywordNoteField = value;
                    this.RaisePropertyChanged("KeywordNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string KeywordResponse {
            get {
                return this.KeywordResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordResponseField, value) != true)) {
                    this.KeywordResponseField = value;
                    this.RaisePropertyChanged("KeywordResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CallbackURL {
            get {
                return this.CallbackURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CallbackURLField, value) != true)) {
                    this.CallbackURLField = value;
                    this.RaisePropertyChanged("CallbackURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int App_Identifier {
            get {
                return this.App_IdentifierField;
            }
            set {
                if ((this.App_IdentifierField.Equals(value) != true)) {
                    this.App_IdentifierField = value;
                    this.RaisePropertyChanged("App_Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string SubscribedResponse {
            get {
                return this.SubscribedResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscribedResponseField, value) != true)) {
                    this.SubscribedResponseField = value;
                    this.RaisePropertyChanged("SubscribedResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int KeywordTypeID {
            get {
                return this.KeywordTypeIDField;
            }
            set {
                if ((this.KeywordTypeIDField.Equals(value) != true)) {
                    this.KeywordTypeIDField = value;
                    this.RaisePropertyChanged("KeywordTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string KeywordType {
            get {
                return this.KeywordTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordTypeField, value) != true)) {
                    this.KeywordTypeField = value;
                    this.RaisePropertyChanged("KeywordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int IsAutoSubscribe {
            get {
                return this.IsAutoSubscribeField;
            }
            set {
                if ((this.IsAutoSubscribeField.Equals(value) != true)) {
                    this.IsAutoSubscribeField = value;
                    this.RaisePropertyChanged("IsAutoSubscribe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSVerificationTypeResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSVerificationTypeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerficationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerficationType {
            get {
                return this.VerficationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerficationTypeField, value) != true)) {
                    this.VerficationTypeField = value;
                    this.RaisePropertyChanged("VerficationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReversePhoneResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSReversePhoneResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSReversePhoneOwner ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IAC2018SQL.GeneralWSProxy.WSReversePhoneOwner Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReversePhoneOwner", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSReversePhoneOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phone_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> is_validField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_calling_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string line_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> is_prepaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> is_commercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSResversePhoneOwnerName[] belongs_toField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSReversePhoneOwnerAddress[] current_addressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSReversePhoneOwnerAddress[] historical_addressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSReversePhoneAssociatedPeople[] associated_peopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] alternate_phonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.ErrorDetails errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] warningsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.phone_numberField, value) != true)) {
                    this.phone_numberField = value;
                    this.RaisePropertyChanged("phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<bool> is_valid {
            get {
                return this.is_validField;
            }
            set {
                if ((this.is_validField.Equals(value) != true)) {
                    this.is_validField = value;
                    this.RaisePropertyChanged("is_valid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string country_calling_code {
            get {
                return this.country_calling_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.country_calling_codeField, value) != true)) {
                    this.country_calling_codeField = value;
                    this.RaisePropertyChanged("country_calling_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string line_type {
            get {
                return this.line_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.line_typeField, value) != true)) {
                    this.line_typeField = value;
                    this.RaisePropertyChanged("line_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string carrier {
            get {
                return this.carrierField;
            }
            set {
                if ((object.ReferenceEquals(this.carrierField, value) != true)) {
                    this.carrierField = value;
                    this.RaisePropertyChanged("carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<bool> is_prepaid {
            get {
                return this.is_prepaidField;
            }
            set {
                if ((this.is_prepaidField.Equals(value) != true)) {
                    this.is_prepaidField = value;
                    this.RaisePropertyChanged("is_prepaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Nullable<bool> is_commercial {
            get {
                return this.is_commercialField;
            }
            set {
                if ((this.is_commercialField.Equals(value) != true)) {
                    this.is_commercialField = value;
                    this.RaisePropertyChanged("is_commercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public IAC2018SQL.GeneralWSProxy.WSResversePhoneOwnerName[] belongs_to {
            get {
                return this.belongs_toField;
            }
            set {
                if ((object.ReferenceEquals(this.belongs_toField, value) != true)) {
                    this.belongs_toField = value;
                    this.RaisePropertyChanged("belongs_to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public IAC2018SQL.GeneralWSProxy.WSReversePhoneOwnerAddress[] current_addresses {
            get {
                return this.current_addressesField;
            }
            set {
                if ((object.ReferenceEquals(this.current_addressesField, value) != true)) {
                    this.current_addressesField = value;
                    this.RaisePropertyChanged("current_addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public IAC2018SQL.GeneralWSProxy.WSReversePhoneOwnerAddress[] historical_addresses {
            get {
                return this.historical_addressesField;
            }
            set {
                if ((object.ReferenceEquals(this.historical_addressesField, value) != true)) {
                    this.historical_addressesField = value;
                    this.RaisePropertyChanged("historical_addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public IAC2018SQL.GeneralWSProxy.WSReversePhoneAssociatedPeople[] associated_people {
            get {
                return this.associated_peopleField;
            }
            set {
                if ((object.ReferenceEquals(this.associated_peopleField, value) != true)) {
                    this.associated_peopleField = value;
                    this.RaisePropertyChanged("associated_people");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string[] alternate_phones {
            get {
                return this.alternate_phonesField;
            }
            set {
                if ((object.ReferenceEquals(this.alternate_phonesField, value) != true)) {
                    this.alternate_phonesField = value;
                    this.RaisePropertyChanged("alternate_phones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public IAC2018SQL.GeneralWSProxy.ErrorDetails error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string[] warnings {
            get {
                return this.warningsField;
            }
            set {
                if ((object.ReferenceEquals(this.warningsField, value) != true)) {
                    this.warningsField = value;
                    this.RaisePropertyChanged("warnings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDetails", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class ErrorDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSResversePhoneOwnerName", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSResversePhoneOwnerName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middlenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string age_rangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string link_to_phone_start_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                if ((object.ReferenceEquals(this.middlenameField, value) != true)) {
                    this.middlenameField = value;
                    this.RaisePropertyChanged("middlename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string age_range {
            get {
                return this.age_rangeField;
            }
            set {
                if ((object.ReferenceEquals(this.age_rangeField, value) != true)) {
                    this.age_rangeField = value;
                    this.RaisePropertyChanged("age_range");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string link_to_phone_start_date {
            get {
                return this.link_to_phone_start_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.link_to_phone_start_dateField, value) != true)) {
                    this.link_to_phone_start_dateField = value;
                    this.RaisePropertyChanged("link_to_phone_start_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReversePhoneOwnerAddress", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSReversePhoneOwnerAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string location_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string street_line_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string street_line_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postal_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zip4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string state_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2018SQL.GeneralWSProxy.WSReversePhoneLocation lat_longField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> is_activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string delivery_pointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string link_to_person_start_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string location_type {
            get {
                return this.location_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.location_typeField, value) != true)) {
                    this.location_typeField = value;
                    this.RaisePropertyChanged("location_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string street_line_1 {
            get {
                return this.street_line_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.street_line_1Field, value) != true)) {
                    this.street_line_1Field = value;
                    this.RaisePropertyChanged("street_line_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string street_line_2 {
            get {
                return this.street_line_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.street_line_2Field, value) != true)) {
                    this.street_line_2Field = value;
                    this.RaisePropertyChanged("street_line_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.postal_codeField, value) != true)) {
                    this.postal_codeField = value;
                    this.RaisePropertyChanged("postal_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4 {
            get {
                return this.zip4Field;
            }
            set {
                if ((object.ReferenceEquals(this.zip4Field, value) != true)) {
                    this.zip4Field = value;
                    this.RaisePropertyChanged("zip4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string state_code {
            get {
                return this.state_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.state_codeField, value) != true)) {
                    this.state_codeField = value;
                    this.RaisePropertyChanged("state_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.country_codeField, value) != true)) {
                    this.country_codeField = value;
                    this.RaisePropertyChanged("country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public IAC2018SQL.GeneralWSProxy.WSReversePhoneLocation lat_long {
            get {
                return this.lat_longField;
            }
            set {
                if ((object.ReferenceEquals(this.lat_longField, value) != true)) {
                    this.lat_longField = value;
                    this.RaisePropertyChanged("lat_long");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public System.Nullable<bool> is_active {
            get {
                return this.is_activeField;
            }
            set {
                if ((this.is_activeField.Equals(value) != true)) {
                    this.is_activeField = value;
                    this.RaisePropertyChanged("is_active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string delivery_point {
            get {
                return this.delivery_pointField;
            }
            set {
                if ((object.ReferenceEquals(this.delivery_pointField, value) != true)) {
                    this.delivery_pointField = value;
                    this.RaisePropertyChanged("delivery_point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string link_to_person_start_date {
            get {
                return this.link_to_person_start_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.link_to_person_start_dateField, value) != true)) {
                    this.link_to_person_start_dateField = value;
                    this.RaisePropertyChanged("link_to_person_start_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReversePhoneAssociatedPeople", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSReversePhoneAssociatedPeople : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string relationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string relation {
            get {
                return this.relationField;
            }
            set {
                if ((object.ReferenceEquals(this.relationField, value) != true)) {
                    this.relationField = value;
                    this.RaisePropertyChanged("relation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReversePhoneLocation", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSReversePhoneLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accuracyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string accuracy {
            get {
                return this.accuracyField;
            }
            set {
                if ((object.ReferenceEquals(this.accuracyField, value) != true)) {
                    this.accuracyField = value;
                    this.RaisePropertyChanged("accuracy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SBTService/ServiceContracts/", ConfigurationName="GeneralWSProxy.IGroup")]
    public interface IGroup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCellularCarrier", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCellularCarrierResponse")]
        IAC2018SQL.GeneralWSProxy.WSReportInboundMessagesResponse GetCellularCarrier(string securityToken, string[] phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCellularCarrier", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCellularCarrierResponse")]
        System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSReportInboundMessagesResponse> GetCellularCarrierAsync(string securityToken, string[] phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCarrierLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCarrierLookupResponse")]
        IAC2018SQL.GeneralWSProxy.WSCarrierLookupResponse GetCarrierLookup(string securityToken, string[] phone, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCarrierLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCarrierLookupResponse")]
        System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSCarrierLookupResponse> GetCarrierLookupAsync(string securityToken, string[] phone, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetOrgTree", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetOrgTreeResponse")]
        IAC2018SQL.GeneralWSProxy.WSOrganizationTreeResponse GetOrgTree(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetOrgTree", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetOrgTreeResponse")]
        System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSOrganizationTreeResponse> GetOrgTreeAsync(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReadVerificationType", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReadVerificationTypeResponse")]
        IAC2018SQL.GeneralWSProxy.WSVerificationTypeResponse ReadVerificationType(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReadVerificationType", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReadVerificationTypeResponse")]
        System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSVerificationTypeResponse> ReadVerificationTypeAsync(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReversePhoneLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReversePhoneLookupResponse")]
        IAC2018SQL.GeneralWSProxy.WSReversePhoneResponse ReversePhoneLookup(string securityToken, string orgCode, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReversePhoneLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReversePhoneLookupResponse")]
        System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSReversePhoneResponse> ReversePhoneLookupAsync(string securityToken, string orgCode, string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupChannel : IAC2018SQL.GeneralWSProxy.IGroup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupClient : System.ServiceModel.ClientBase<IAC2018SQL.GeneralWSProxy.IGroup>, IAC2018SQL.GeneralWSProxy.IGroup {
        
        public GroupClient() {
        }
        
        public GroupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IAC2018SQL.GeneralWSProxy.WSReportInboundMessagesResponse GetCellularCarrier(string securityToken, string[] phone) {
            return base.Channel.GetCellularCarrier(securityToken, phone);
        }
        
        public System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSReportInboundMessagesResponse> GetCellularCarrierAsync(string securityToken, string[] phone) {
            return base.Channel.GetCellularCarrierAsync(securityToken, phone);
        }
        
        public IAC2018SQL.GeneralWSProxy.WSCarrierLookupResponse GetCarrierLookup(string securityToken, string[] phone, string orgCode) {
            return base.Channel.GetCarrierLookup(securityToken, phone, orgCode);
        }
        
        public System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSCarrierLookupResponse> GetCarrierLookupAsync(string securityToken, string[] phone, string orgCode) {
            return base.Channel.GetCarrierLookupAsync(securityToken, phone, orgCode);
        }
        
        public IAC2018SQL.GeneralWSProxy.WSOrganizationTreeResponse GetOrgTree(string securityToken, string orgCode) {
            return base.Channel.GetOrgTree(securityToken, orgCode);
        }
        
        public System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSOrganizationTreeResponse> GetOrgTreeAsync(string securityToken, string orgCode) {
            return base.Channel.GetOrgTreeAsync(securityToken, orgCode);
        }
        
        public IAC2018SQL.GeneralWSProxy.WSVerificationTypeResponse ReadVerificationType(string securityToken, string orgCode) {
            return base.Channel.ReadVerificationType(securityToken, orgCode);
        }
        
        public System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSVerificationTypeResponse> ReadVerificationTypeAsync(string securityToken, string orgCode) {
            return base.Channel.ReadVerificationTypeAsync(securityToken, orgCode);
        }
        
        public IAC2018SQL.GeneralWSProxy.WSReversePhoneResponse ReversePhoneLookup(string securityToken, string orgCode, string phone) {
            return base.Channel.ReversePhoneLookup(securityToken, orgCode, phone);
        }
        
        public System.Threading.Tasks.Task<IAC2018SQL.GeneralWSProxy.WSReversePhoneResponse> ReversePhoneLookupAsync(string securityToken, string orgCode, string phone) {
            return base.Channel.ReversePhoneLookupAsync(securityToken, orgCode, phone);
        }
    }
}
