//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAC2021SQL.SubscriberWSProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberDetails", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class SubscriberDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SubcribeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubscribedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateAbbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UnSubcribedateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LandLine {
            get {
                return this.LandLineField;
            }
            set {
                if ((object.ReferenceEquals(this.LandLineField, value) != true)) {
                    this.LandLineField = value;
                    this.RaisePropertyChanged("LandLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.DateTime SubcribeDate {
            get {
                return this.SubcribeDateField;
            }
            set {
                if ((this.SubcribeDateField.Equals(value) != true)) {
                    this.SubcribeDateField = value;
                    this.RaisePropertyChanged("SubcribeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public int SubscribedType {
            get {
                return this.SubscribedTypeField;
            }
            set {
                if ((this.SubscribedTypeField.Equals(value) != true)) {
                    this.SubscribedTypeField = value;
                    this.RaisePropertyChanged("SubscribedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StateAbbr {
            get {
                return this.StateAbbrField;
            }
            set {
                if ((object.ReferenceEquals(this.StateAbbrField, value) != true)) {
                    this.StateAbbrField = value;
                    this.RaisePropertyChanged("StateAbbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Street2 {
            get {
                return this.Street2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street2Field, value) != true)) {
                    this.Street2Field = value;
                    this.RaisePropertyChanged("Street2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public System.DateTime UnSubcribedate {
            get {
                return this.UnSubcribedateField;
            }
            set {
                if ((this.UnSubcribedateField.Equals(value) != true)) {
                    this.UnSubcribedateField = value;
                    this.RaisePropertyChanged("UnSubcribedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSSubscriberResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSSubscriberResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2021SQL.SubscriberWSProxy.SubscriberDetails ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IAC2021SQL.SubscriberWSProxy.SubscriberDetails Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSUnsubscriberResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSUnsubscriberResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSSubscribersStatusResponse", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class WSSubscribersStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IAC2021SQL.SubscriberWSProxy.SubscriberStatus[] ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IAC2021SQL.SubscriberWSProxy.SubscriberStatus[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberStatus", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class SubscriberStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarrierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OptInMethodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptInMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatestOptInOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CarrierID {
            get {
                return this.CarrierIDField;
            }
            set {
                if ((this.CarrierIDField.Equals(value) != true)) {
                    this.CarrierIDField = value;
                    this.RaisePropertyChanged("CarrierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Carrier {
            get {
                return this.CarrierField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierField, value) != true)) {
                    this.CarrierField = value;
                    this.RaisePropertyChanged("Carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int OptInMethodID {
            get {
                return this.OptInMethodIDField;
            }
            set {
                if ((this.OptInMethodIDField.Equals(value) != true)) {
                    this.OptInMethodIDField = value;
                    this.RaisePropertyChanged("OptInMethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string OptInMethod {
            get {
                return this.OptInMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.OptInMethodField, value) != true)) {
                    this.OptInMethodField = value;
                    this.RaisePropertyChanged("OptInMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string OptInDate {
            get {
                return this.OptInDateField;
            }
            set {
                if ((object.ReferenceEquals(this.OptInDateField, value) != true)) {
                    this.OptInDateField = value;
                    this.RaisePropertyChanged("OptInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string LatestOptInOutDate {
            get {
                return this.LatestOptInOutDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LatestOptInOutDateField, value) != true)) {
                    this.LatestOptInOutDateField = value;
                    this.RaisePropertyChanged("LatestOptInOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriberInfo", Namespace="http://SBTAPIService/DataContract/")]
    [System.SerializableAttribute()]
    public partial class SubscriberInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Street2 {
            get {
                return this.Street2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street2Field, value) != true)) {
                    this.Street2Field = value;
                    this.RaisePropertyChanged("Street2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CustomField1 {
            get {
                return this.CustomField1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField1Field, value) != true)) {
                    this.CustomField1Field = value;
                    this.RaisePropertyChanged("CustomField1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustomField2 {
            get {
                return this.CustomField2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField2Field, value) != true)) {
                    this.CustomField2Field = value;
                    this.RaisePropertyChanged("CustomField2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CustomField3 {
            get {
                return this.CustomField3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField3Field, value) != true)) {
                    this.CustomField3Field = value;
                    this.RaisePropertyChanged("CustomField3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PrivateCode {
            get {
                return this.PrivateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateCodeField, value) != true)) {
                    this.PrivateCodeField = value;
                    this.RaisePropertyChanged("PrivateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SBTService/ServiceContracts/", ConfigurationName="SubscriberWSProxy.ISubscriber")]
    public interface ISubscriber {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/Subscribe", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/SubscribeResponse")]
        IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse Subscribe(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/Subscribe", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/SubscribeResponse")]
        System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse> SubscribeAsync(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/UnSubscribe", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/UnSubscribeResponse")]
        IAC2021SQL.SubscriberWSProxy.WSUnsubscriberResponse UnSubscribe(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/UnSubscribe", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/UnSubscribeResponse")]
        System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSUnsubscriberResponse> UnSubscribeAsync(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/GetSubscribersStatus", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/GetSubscribersStatusResponse")]
        IAC2021SQL.SubscriberWSProxy.WSSubscribersStatusResponse GetSubscribersStatus(string securityToken, string orgCode, string[] phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/GetSubscribersStatus", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/GetSubscribersStatusResponse")]
        System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscribersStatusResponse> GetSubscribersStatusAsync(string securityToken, string orgCode, string[] phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriber", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriberResponse")]
        IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse UpdateSubscriber(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriber", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriberResponse")]
        System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse> UpdateSubscriberAsync(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriberByOrg", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriberByOrgResponse")]
        IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse UpdateSubscriberByOrg(string securityToken, string orgCode, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriberByOrg", ReplyAction="http://SBTService/ServiceContracts/ISubscriber/UpdateSubscriberByOrgResponse")]
        System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse> UpdateSubscriberByOrgAsync(string securityToken, string orgCode, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriberChannel : IAC2021SQL.SubscriberWSProxy.ISubscriber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriberClient : System.ServiceModel.ClientBase<IAC2021SQL.SubscriberWSProxy.ISubscriber>, IAC2021SQL.SubscriberWSProxy.ISubscriber {
        
        public SubscriberClient() {
        }
        
        public SubscriberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse Subscribe(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber) {
            return base.Channel.Subscribe(securityToken, subscriber);
        }
        
        public System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse> SubscribeAsync(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber) {
            return base.Channel.SubscribeAsync(securityToken, subscriber);
        }
        
        public IAC2021SQL.SubscriberWSProxy.WSUnsubscriberResponse UnSubscribe(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber) {
            return base.Channel.UnSubscribe(securityToken, subscriber);
        }
        
        public System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSUnsubscriberResponse> UnSubscribeAsync(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberDetails subscriber) {
            return base.Channel.UnSubscribeAsync(securityToken, subscriber);
        }
        
        public IAC2021SQL.SubscriberWSProxy.WSSubscribersStatusResponse GetSubscribersStatus(string securityToken, string orgCode, string[] phone) {
            return base.Channel.GetSubscribersStatus(securityToken, orgCode, phone);
        }
        
        public System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscribersStatusResponse> GetSubscribersStatusAsync(string securityToken, string orgCode, string[] phone) {
            return base.Channel.GetSubscribersStatusAsync(securityToken, orgCode, phone);
        }
        
        public IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse UpdateSubscriber(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber) {
            return base.Channel.UpdateSubscriber(securityToken, subscriber);
        }
        
        public System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse> UpdateSubscriberAsync(string securityToken, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber) {
            return base.Channel.UpdateSubscriberAsync(securityToken, subscriber);
        }
        
        public IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse UpdateSubscriberByOrg(string securityToken, string orgCode, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber) {
            return base.Channel.UpdateSubscriberByOrg(securityToken, orgCode, subscriber);
        }
        
        public System.Threading.Tasks.Task<IAC2021SQL.SubscriberWSProxy.WSSubscriberResponse> UpdateSubscriberByOrgAsync(string securityToken, string orgCode, IAC2021SQL.SubscriberWSProxy.SubscriberInfo subscriber) {
            return base.Channel.UpdateSubscriberByOrgAsync(securityToken, orgCode, subscriber);
        }
    }
}
